# your domain
domain: my-proxy-tool-123.herokuapp.com

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://raw.githubusercontent.com/SakuraVincent/proxypool/master/config/source.yaml
